# Generated by Django 3.1.3 on 2021-01-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledays',
            options={'ordering': ['-effective_date'], 'verbose_name_plural': 'Available Days'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['-effective_date'], 'verbose_name_plural': 'Prices'},
        ),
    ]
