# Generated by Django 3.1.3 on 2020-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_loginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
