# Generated by Django 3.1.3 on 2020-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_loginfo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginfo',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
