# Generated by Django 3.1.3 on 2021-01-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
