# Generated by Django 3.1.3 on 2021-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messages_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
