# Generated by Django 3.1.3 on 2021-01-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210117_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
    ]
