# Generated by Django 3.1.3 on 2021-01-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210117_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Messages'},
        ),
    ]
