# Generated by Django 3.1.3 on 2021-03-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210225_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
