# Generated by Django 4.0.2 on 2022-02-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(upload_to='')),
                ('user_image', models.ImageField(upload_to='')),
                ('by', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('hook', models.CharField(max_length=500)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_link', models.URLField(blank=True, max_length=300, null=True)),
                ('main_paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=300)),
                ('paragraph', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
