# Generated by Django 4.0.2 on 2022-02-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsections',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogsections',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsections',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
