# Generated by Django 4.0.2 on 2022-02-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_conclusion_alter_blogsections_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsections',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
