# Generated by Django 3.1.3 on 2021-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Currency Rates',
            },
        ),
    ]
