# Generated by Django 3.1.3 on 2021-01-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210111_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'time')},
        ),
    ]
