# Generated by Django 3.1.3 on 2021-01-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20210116_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('date', 'time')},
        ),
    ]
