# Generated by Django 3.1.3 on 2021-01-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20210116_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
