# Generated by Django 3.1.3 on 2021-01-27 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_scheme',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart_description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiryMonth',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiryYear',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='response_message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tran_currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tran_total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='resp_status',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
