# Generated by Django 3.1.3 on 2021-01-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
