# Generated by Django 3.1.3 on 2021-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='cart_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
