# Generated by Django 3.1.3 on 2021-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_auto_20210129_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
    ]
