# Generated by Django 3.1.3 on 2021-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_appointments_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='cart_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
