# Generated by Django 3.1.3 on 2021-01-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_auto_20210129_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='tran_currency',
            field=models.CharField(max_length=5),
        ),
    ]
