# Generated by Django 4.0.2 on 2022-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_alter_appointments_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency Rates'},
        ),
    ]
