# Generated by Django 3.1.3 on 2020-11-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=40)),
                ('device', models.CharField(max_length=20)),
                ('device_family', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=40)),
                ('operating_system', models.CharField(max_length=40)),
            ],
        ),
    ]
