# Generated by Django 3.1.3 on 2020-11-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loginfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogInfo',
        ),
    ]
