# Generated by Django 3.1.3 on 2020-11-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableDays',
        ),
    ]
