# Generated by Django 3.1.3 on 2021-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
