# Generated by Django 3.1.3 on 2021-01-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210111_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='response',
        ),
        migrations.AddField(
            model_name='currency',
            name='rates',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
