# Generated by Django 3.1.3 on 2021-01-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20210116_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Currency Rates'},
        ),
    ]
