# Generated by Django 3.1.3 on 2021-01-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointments_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rates',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
