# Generated by Django 3.1.3 on 2021-01-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
