# Generated by Django 3.1.3 on 2021-01-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_auto_20210128_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_key', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
