# Generated by Django 3.1.3 on 2021-01-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_auto_20210130_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
