# Generated by Django 3.1.3 on 2021-01-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_coupon'),
        ('appointments', '0026_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.coupon'),
        ),
    ]
