# Generated by Django 3.1.3 on 2020-11-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='location',
        ),
    ]
