# Generated by Django 3.1.3 on 2021-01-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_info',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
