# Generated by Django 3.1.3 on 2020-11-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201128_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='browser',
        ),
    ]
