# Generated by Django 3.1.3 on 2021-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
